# App instellingen
spring.application.name=backend-vinylshop-springboot-repository

# Database instellingen
POSTGRESQL_DATABASENAME=vinylshop
POSTGRESQL_USERNAME=postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRESQL_DATABASENAME}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}


# Jpa instellingen
spring.jpa.show-sql=true

# forces to generate the data structures
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create